// Words that read well before "Rebel" and say nothing about anyone.
const adjectives = [
  'Furious',
  'Quiet',
  'Restless',
  'Bold',
  'Curious',
  'Daring',
  'Fearless',
  'Gentle',
  'Hopeful',
  'Joyful',
  'Lively',
  'Loyal',
  'Merry',
  'Nimble',
  'Patient',
  'Playful',
  'Proud',
  'Radiant',
  'Sly',
  'Steady',
  'Stubborn',
  'Sunny',
  'Swift',
  'Tireless',
  'Untamed',
  'Vivid',
  'Wild',
  'Witty',
  'Brave',
  'Bright',
  'Calm',
  'Cheeky',
  'Clever',
  'Cosmic',
  'Crafty',
  'Dashing',
  'Eager',
  'Electric',
  'Fierce',
  'Fiery',
  'Free',
  'Friendly',
  'Gallant',
  'Giddy',
  'Glowing',
  'Grand',
  'Happy',
  'Hardy',
  'Honest',
  'Humble',
  'Jolly',
  'Keen',
  'Kind',
  'Lucky',
  'Magnetic',
  'Mighty',
  'Mellow',
  'Mystic',
  'Noble',
  'Peppy',
  'Plucky',
  'Polite',
  'Quick',
  'Quirky',
  'Rapid',
  'Rowdy',
  'Rustic',
  'Sassy',
  'Serene',
  'Sharp',
  'Shiny',
  'Silent',
  'Smiling',
  'Snappy',
  'Sparkling',
  'Spirited',
  'Spry',
  'Stellar',
  'Stormy',
  'Sturdy',
  'Super',
  'Tender',
  'Thrifty',
  'Tough',
  'Tranquil',
  'Upbeat',
  'Valiant',
  'Vibrant',
  'Vigilant',
  'Warm',
  'Wise',
  'Wandering',
  'Whimsical',
  'Zealous',
  'Zesty',
  'Agile',
  'Ardent',
  'Artful',
  'Astute',
  'Audacious',
  'Blazing',
  'Breezy',
  'Buoyant',
  'Candid',
  'Cheerful',
  'Chirpy',
  'Colorful',
  'Cunning',
  'Dazzling',
  'Defiant',
  'Dynamic',
  'Earnest',
  'Epic',
  'Feisty',
  'Fluffy',
  'Frank',
  'Gutsy',
  'Heroic',
  'Inventive',
  'Jazzy',
  'Jubilant',
  'Lucid',
  'Maverick',
  'Mischievous',
  'Moody',
  'Nifty',
  'Optimistic',
  'Perky',
  'Quixotic',
  'Rebellious',
  'Resolute',
  'Rogue',
  'Scrappy',
  'Spunky',
  'Stalwart',
  'Tenacious',
  'Unruly',
  'Vocal',
  'Wily',
  'Zany',
] as const

/** A pseudonym none of `taken` holds: an adjective and "Rebel", picked with
 * `random` among those free, and numbered once every adjective is taken
 * (R-GAME-15). */
export function pickPseudonym(
  taken: ReadonlySet<string>,
  random: () => number,
): string {
  for (let round = 1; ; round += 1) {
    const suffix = round === 1 ? '' : ` ${String(round)}`
    const free = adjectives
      .map((adjective) => `${adjective} Rebel${suffix}`)
      .filter((name) => !taken.has(name))
    const pick = free[Math.floor(random() * free.length)]
    if (pick !== undefined) return pick
  }
}
