import type { SeedTrend } from '../types.js'

/** The 8 Corporate Rebels trends with the prototype's keywords: strong ones
 * weigh 6, weak ones 1 (design §5, §6.1, R-ASK-5). */
export const trends: SeedTrend[] = [
  {
    id: '01',
    short: 'Purpose & Values',
    from: 'Profit',
    peers: 12,
    keywords: {
      strong: ['purpose', 'values', 'mission statement', 'meaning'],
      weak: [
        'purpose',
        'values',
        'mission',
        'meaning',
        'culture fit',
        'recruit',
        'brand',
      ],
    },
  },
  {
    id: '02',
    short: 'Network of Teams',
    from: 'Hierarchical Pyramid',
    peers: 34,
    keywords: {
      strong: [
        'org chart',
        'shadow organi',
        'shadow organis',
        'middle management',
        'network of teams',
        'silo',
        'reorg',
      ],
      weak: [
        'structure',
        'hierarch',
        'circle',
        'team',
        'silo',
        'reorg',
        'pyramid',
        'shadow',
        'department',
      ],
    },
  },
  {
    id: '03',
    short: 'Supportive Leadership',
    from: 'Directive Leadership',
    peers: 27,
    keywords: {
      strong: [
        'micromanag',
        'leadership means',
        'management position',
        'coach',
        'directive',
      ],
      weak: ['leader', 'manager', 'boss', 'command', 'let go', 'supervisor'],
    },
  },
  {
    id: '04',
    short: 'Experiment & Adapt',
    from: 'Plan & Predict',
    peers: 15,
    keywords: {
      strong: [
        'budget cycle',
        'annual budget',
        'forecast',
        'experiment',
        'pilot',
        'okr',
      ],
      weak: [
        'budget',
        'plan',
        'forecast',
        'experiment',
        'pilot',
        'agile',
        'roadmap',
      ],
    },
  },
  {
    id: '05',
    short: 'Freedom & Trust',
    from: 'Rules & Control',
    peers: 21,
    keywords: {
      strong: [
        'remote',
        'hybrid',
        'office days',
        'vacation',
        'working hours',
        'four-day',
        'approval',
      ],
      weak: [
        'trust',
        'freedom',
        'rule',
        'policy',
        'autonom',
        'control',
        'hours',
      ],
    },
  },
  {
    id: '06',
    short: 'Distributed Decision Making',
    from: 'Centralized Authority',
    peers: 29,
    keywords: {
      strong: [
        'who decides',
        'who can decide',
        'who actually can decide',
        'decision-making',
        'decision making',
        'decision rights',
        'mandate',
        'advice process',
        'consent',
      ],
      weak: [
        'decision',
        'decide',
        'authority',
        'mandate',
        'consent',
        'power',
        'empower',
        'escalat',
      ],
    },
  },
  {
    id: '07',
    short: 'Radical Transparency',
    from: 'Secrecy',
    peers: 18,
    keywords: {
      strong: [
        'salary',
        'salaries',
        'pay model',
        'compensation',
        'remuneration',
        'bonus',
        'open book',
        'transparen',
        'wage',
      ],
      weak: [
        'transparen',
        'salary',
        'pay',
        'compensation',
        'financial',
        'secret',
        'reward',
        'bonus',
      ],
    },
  },
  {
    id: '08',
    short: 'Talents & Mastery',
    from: 'Job Descriptions',
    peers: 23,
    keywords: {
      strong: [
        'performance review',
        'peer feedback',
        'job description',
        'job title',
        'appraisal',
        'promotion',
        'career path',
        'talent',
      ],
      weak: [
        'talent',
        'job',
        'review',
        'feedback',
        'career',
        'promotion',
        'development',
        'mastery',
      ],
    },
  },
]
