import type { SeedMember } from '../types.js'

/** The dev admin `npm run dev` prints a sign-in link for (R-DEV-6). */
export const DEV_ADMIN_EMAIL = 'admin@rebel-match.invalid'

/** The fictional roster from the prototype (design §6.3, R-SEED-2), on a
 * non-routable domain so no real person can be emailed (constitution §5). */
export const people: SeedMember[] = [
  {
    email: DEV_ADMIN_EMAIL,
    name: 'Dev Admin',
    jobTitle: 'Developer',
    org: 'Rebel Match',
    sector: 'software-technology',
    companySize: '1-10',
    roles: ['member', 'admin'],
  },
  {
    email: 'marieke.de.wit@example.invalid',
    name: 'Marieke de Wit',
    jobTitle: 'People lead',
    org: 'Kade Collectief',
    sector: 'agency-consulting',
    companySize: '51-250',
    roles: ['member'],
  },
  {
    email: 'tobias.renner@example.invalid',
    name: 'Tobias Renner',
    jobTitle: 'CFO',
    org: 'Novaflex',
    sector: 'manufacturing',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'ana.ferreira@example.invalid',
    name: 'Ana Ferreira',
    jobTitle: 'Ops director',
    org: 'Meridian Care',
    sector: 'healthcare',
    companySize: '1001+',
    roles: ['member'],
  },
  {
    email: 'jonas.brand@example.invalid',
    name: 'Jonas Brand',
    jobTitle: 'Transformation lead',
    org: 'Werkhaus',
    sector: 'industrial-services',
    companySize: '1001+',
    roles: ['member'],
  },
  {
    email: 'priya.raman@example.invalid',
    name: 'Priya Raman',
    jobTitle: 'Head of workplace',
    org: 'Kestrel Digital',
    sector: 'software-technology',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'lars.petersen@example.invalid',
    name: 'Lars Petersen',
    jobTitle: 'Finance partner',
    org: 'Nordlys',
    sector: 'energy-utilities',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'nadia.osei@example.invalid',
    name: 'Nadia Osei',
    jobTitle: 'Culture lead',
    org: 'Baumann Bau',
    sector: 'construction',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'ruben.vos@example.invalid',
    name: 'Ruben Vos',
    jobTitle: 'Managing director',
    org: 'Helder Groep',
    sector: 'logistics',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'aline.dubois@example.invalid',
    name: 'Aline Dubois',
    jobTitle: 'People lead',
    org: 'Cartographe',
    sector: 'agency-consulting',
    companySize: '51-250',
    roles: ['member'],
  },
  {
    email: 'sanne.kuipers@example.invalid',
    name: 'Sanne Kuipers',
    jobTitle: 'Ops lead',
    org: 'Vaartlicht',
    sector: 'healthcare',
    companySize: '1001+',
    roles: ['member'],
  },
  {
    email: 'milan.horvat@example.invalid',
    name: 'Milan Horvat',
    jobTitle: 'Team coach',
    org: 'Sova Systems',
    sector: 'software-technology',
    companySize: '51-250',
    roles: ['member'],
  },
  {
    email: 'elena.marchetti@example.invalid',
    name: 'Elena Marchetti',
    jobTitle: 'HR business partner',
    org: 'Terrafino',
    sector: 'food-agriculture',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'ola.nyberg@example.invalid',
    name: 'Ola Nyberg',
    jobTitle: 'Site manager',
    org: 'Björk Industri',
    sector: 'manufacturing',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'yusuf.kaya@example.invalid',
    name: 'Yusuf Kaya',
    jobTitle: 'Product director',
    org: 'Arcadia Labs',
    sector: 'software-technology',
    companySize: '251-1000',
    roles: ['member'],
  },
  {
    email: 'hanna.vogt@example.invalid',
    name: 'Hanna Vogt',
    jobTitle: 'Team lead',
    org: 'Lindquist',
    sector: 'retail',
    companySize: '1001+',
    roles: ['member'],
  },
  {
    email: 'diego.salas@example.invalid',
    name: 'Diego Salas',
    jobTitle: 'Head of people',
    org: 'Puerto Verde',
    sector: 'logistics',
    companySize: '251-1000',
    roles: ['member'],
  },
]
