import type { SeedMember } from '../types.js'

/** The dev admin `npm run dev` prints a sign-in link for (R-DEV-6). */
export const DEV_ADMIN_EMAIL = 'admin@rebel-match.invalid'

/** The fictional roster from the prototype (design §6.3, R-SEED-2), on a
 * non-routable domain so no real person can be emailed (constitution §5). */
export const people: SeedMember[] = [
  {
    email: DEV_ADMIN_EMAIL,
    name: 'Dev Admin',
    jobTitle: 'Developer',
    org: 'Rebel Match',
    sector: 'Software',
    roles: ['member', 'admin'],
  },
  {
    email: 'marieke.de.wit@example.invalid',
    name: 'Marieke de Wit',
    jobTitle: 'People lead',
    org: 'Kade Collectief',
    sector: 'Agency · 90',
    roles: ['member'],
  },
  {
    email: 'tobias.renner@example.invalid',
    name: 'Tobias Renner',
    jobTitle: 'CFO',
    org: 'Novaflex',
    sector: 'Manufacturing · 480',
    roles: ['member'],
  },
  {
    email: 'ana.ferreira@example.invalid',
    name: 'Ana Ferreira',
    jobTitle: 'Ops director',
    org: 'Meridian Care',
    sector: 'Healthcare · 1,200',
    roles: ['member'],
  },
  {
    email: 'jonas.brand@example.invalid',
    name: 'Jonas Brand',
    jobTitle: 'Transformation lead',
    org: 'Werkhaus',
    sector: 'Industrial services · 2,300',
    roles: ['member'],
  },
  {
    email: 'priya.raman@example.invalid',
    name: 'Priya Raman',
    jobTitle: 'Head of workplace',
    org: 'Kestrel Digital',
    sector: 'Software · 260',
    roles: ['member'],
  },
  {
    email: 'lars.petersen@example.invalid',
    name: 'Lars Petersen',
    jobTitle: 'Finance partner',
    org: 'Nordlys',
    sector: 'Energy · 700',
    roles: ['member'],
  },
  {
    email: 'nadia.osei@example.invalid',
    name: 'Nadia Osei',
    jobTitle: 'Culture lead',
    org: 'Baumann Bau',
    sector: 'Construction · 340',
    roles: ['member'],
  },
  {
    email: 'ruben.vos@example.invalid',
    name: 'Ruben Vos',
    jobTitle: 'Managing director',
    org: 'Helder Groep',
    sector: 'Logistics · 610',
    roles: ['member'],
  },
  {
    email: 'aline.dubois@example.invalid',
    name: 'Aline Dubois',
    jobTitle: 'People lead',
    org: 'Cartographe',
    sector: 'Agency · 90',
    roles: ['member'],
  },
  {
    email: 'sanne.kuipers@example.invalid',
    name: 'Sanne Kuipers',
    jobTitle: 'Ops lead',
    org: 'Vaartlicht',
    sector: 'Healthcare · 1,200',
    roles: ['member'],
  },
  {
    email: 'milan.horvat@example.invalid',
    name: 'Milan Horvat',
    jobTitle: 'Team coach',
    org: 'Sova Systems',
    sector: 'Software · 150',
    roles: ['member'],
  },
  {
    email: 'elena.marchetti@example.invalid',
    name: 'Elena Marchetti',
    jobTitle: 'HR business partner',
    org: 'Terrafino',
    sector: 'Food · 900',
    roles: ['member'],
  },
  {
    email: 'ola.nyberg@example.invalid',
    name: 'Ola Nyberg',
    jobTitle: 'Site manager',
    org: 'Björk Industri',
    sector: 'Manufacturing · 520',
    roles: ['member'],
  },
  {
    email: 'yusuf.kaya@example.invalid',
    name: 'Yusuf Kaya',
    jobTitle: 'Product director',
    org: 'Arcadia Labs',
    sector: 'Software · 310',
    roles: ['member'],
  },
  {
    email: 'hanna.vogt@example.invalid',
    name: 'Hanna Vogt',
    jobTitle: 'Team lead',
    org: 'Lindquist',
    sector: 'Retail · 1,400',
    roles: ['member'],
  },
  {
    email: 'diego.salas@example.invalid',
    name: 'Diego Salas',
    jobTitle: 'Head of people',
    org: 'Puerto Verde',
    sector: 'Logistics · 400',
    roles: ['member'],
  },
]
